### ISSUE TITLE
prior_latent

### ISSUE THREAD

**Issue by ZhouCX117** [alzayats/UDnet#1]
Hi, thanks for your excellent work! I don't understand why 'pr_latent_u = u_mu + u_sigma * 0' in the UDnet.py? Could you give me a favor?

**Comment by alzayats** [comment]
Thank you for your kind words! The line of code pr_latent_u = u_mu + u_sigma * 0 in UDnet.py is related to the probabilistic nature of UDnet. In the training stage, the input image and its corresponding reference image are used to learn the posterior distributions of the latent codes as shown in equations 7 and 8.

Equation 7 represents the distribution of the feature activations in the UDnet’s conditional variational autoencoder (cVAE) module. The distribution is assumed to be normal with mean u_mu and variance u_sigma^2. The mean and variance are functions of the input image and the reference map generated by the statistically guided multi-colour space stretch (SGMCSS) module.

In this line of code, pr_latent_u is assigned the value of u_mu, which represents the mean of the distribution. The term u_sigma * 0 is equal to zero, so it does not affect the value of pr_latent_u. This means that pr_latent_u is a deterministic value equal to the mean of the distribution, rather than a random sample from the distribution.

Please refer to the paper for more details.  https://arxiv.org/pdf/2212.08983.pdf

**Comment by ZhouCX117** [comment]
Thanks for your quick reply! I got it! Have a good day!
